### Create a meeting
POST http://127.0.0.1:8000/meetings/
Content-Type: application/json

{
  "user_email": "rohitvalanki@gmail.com",
  "meeting_subject": "Meeting Subject",
  "meeting_transcript": "Team Meetings 2",
  "meeting_summary": "Discussed project milestones and deadlines.",
  "meeting_recipients": ["recipient1@example.com", "recipient2@example.com"],
  "meeting_date": "2024-10-05T14:00:00Z"
}


### Retrieve meetings for the user
GET http://127.0.0.1:8000/meetings/rohitvalanki@gmail.com/
