name: Django CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd backend/kmp_backend
        python manage.py test

    - name: Start Backend Server
      run: |
        cd backend
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements 
        cd kmp_backend
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver

    - name: Start Content Server 
      run: |
        cd frontend 
        npm install
        npm run dev 

    - name: Testing Frontend
      run: |
        cd frontend
        python seleniumtesting.py 