name: Svelte CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        node-version: [21.7.3, 22.5.1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install Dependencies  
      run: |
        cd frontend
        npm install

    - name: Run tests
      run: |
        cd frontend
        npm test

    - name: Build project
      run: |
        cd frontend 
        npm run dev